name: "Upgrade Gradle"
description: "Upgrade the used gradle wrapper to the current version"
inputs:
  distribution-type:
    description: >
      The used distribution type for the wrapper
      Possible values: bin, all, default (action doesn't specify the distribution type explicitly)
      Default: default
    required: false
    default: "default"
  release-channel:
    description: >
      The used release channel to load the current version from.
      Possible values: current, release-candidate, nightly, release-nightly
      Default: current
    required: false
    default: "current"
outputs:
  gradle-version:
    description: "the latest gradle version"
    value: ${{ steps.upgrade-gradle.outputs.gradle-version }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/upgrade-gradle.sh ${{ inputs.distribution-type }} ${{ inputs.release-channel }}
      id: upgrade-gradle
      shell: bash

branding:
  icon: arrow-up-circle
  color: green
